version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-fuel_db}
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fuel_db"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      NODE_ENV: development
      TZ: UTC
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://127.0.0.1:3000/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 90s
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      RUN_TESTS: "true"
      NODE_ENV: test
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./test:/app/test
    command: ["/bin/bash", "/entrypoint.sh"]

volumes:
  postgres_data: